export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";

export const SET_SELECTED_USER_ID = "SET_SELECTED_USER_ID";

export const ADD_PERIODIC_PRESSURE_TEST = "ADD_PERIODIC_PRESSURE_TEST";
export const DELETE_PERIODIC_PRESSURE_TEST = "DELETE_PERIODIC_PRESSURE_TEST";

export const EDIT_DAILY_VALUES = "EDIT_DAILY_VALUES";
export const SET_OMITTED_DAILY_TEST = "SET_OMITTED_DAILY_TEST";
export const UPDATE_NUMBER_OF_TOTAL_AND_DONE_TESTS_AND_STATE =
  "UPDATE_NUMBER_OF_TOTAL_AND_DONE_TESTS_AND_STATE";

export const CALCULATE_AVERAGE_RESULTS = "CALCULATE_AVERAGE_RESULTS";
